import '../app_colors/all_colors_export.dart';
import '../extend_theme/text_theme_extend.dart';

//light
const textThemeLightExtension = TextThemeExtend(
  txtPrimaryColor: appPrimaryColor,
  txtPrimaryColorChangeable: appPrimaryColor,
  txtPrimaryColorFirst: appPrimaryColorFirst,
  txtPrimaryColorSecond: appPrimaryColorSecond,
  txtPrimaryColorThird: appPrimaryColorSecond,
  txtSecondaryColor: appSecondaryColor,
  txtSecondaryColorChangeable: appSecondaryColor,
  txtSecondaryColorFirst: appSecondaryColorFirst,
  txtSecondaryColorSecond: appSecondaryColorSecond,
  txtSecondaryColorThird: appSecondaryColorThird,
  txtRedColor: txtRedColor,
  txtColorFulFirst: txtColorfulLightFirst,
  txtColorFulSecond: txtColorfulLightSecond,
  txtColorFulThird: txtColorfulLightThird,
  txtColorFulFourth: txtColorfulLightFourth,
  txtColorFulFifth: txtColorfulLightFifth,
  txtColorBlack: txtColorBlackLight,
  txtColorWhite: txtColorWhiteLight,
  txtBodyColorLarge: txtBodyColorLightLarge,
  txtBodyColorMoreMedium: txtBodyColorLightMoreMedium,
  txtBodyColorMedium: txtBodyColorLightMedium,
  txtBodyColorLessMedium: txtBodyColorLightLessMedium,
  txtBodyColorSmall: txtBodyColorLightSmall,
  txtBodyColorLessSmall: txtBodyColorLightLessSmall,
  txtLabelColorLarge: txtLabelColorLightLarge,
  txtLabelColorMoreMedium: txtLabelColorLightMoreMedium,
  txtLabelColorMedium: txtLabelColorLightMedium,
  txtLabelColorLessMedium: txtLabelColorLightLessMedium,
  txtLabelColorSmall: txtLabelColorLightLessMedium,
);


//dark
const textThemeDarkExtension = TextThemeExtend(
  txtPrimaryColor: whiteOnly,
  txtPrimaryColorChangeable: whiteOnly,
  txtPrimaryColorFirst: whiteOnly,
  txtPrimaryColorSecond: whiteOnly,
  txtPrimaryColorThird: whiteOnly,
  txtSecondaryColor: whiteOnly,
  txtSecondaryColorChangeable: whiteOnly,
  txtSecondaryColorFirst: whiteOnly,
  txtSecondaryColorSecond: whiteOnly,
  txtSecondaryColorThird: whiteOnly,
  txtRedColor: whiteOnly,
  txtColorFulFirst: whiteOnly,
  txtColorFulSecond: whiteOnly,
  txtColorFulThird: whiteOnly,
  txtColorFulFourth: whiteOnly,
  txtColorFulFifth: whiteOnly,
  txtColorBlack: txtColorWhiteDark,
  txtColorWhite: txtColorBlackDark,
  txtBodyColorLarge: whiteOnly,
  txtBodyColorMoreMedium: whiteOnly,
  txtBodyColorMedium: whiteOnly,
  txtBodyColorLessMedium: whiteOnly,
  txtBodyColorSmall: whiteOnly,
  txtBodyColorLessSmall: whiteOnly,
  txtLabelColorLarge: whiteOnly,
  txtLabelColorMoreMedium: txtLabelColorDarkMoreMedium,
  txtLabelColorMedium: txtLabelColorDarkMedium,
  txtLabelColorLessMedium: whiteOnly,
  txtLabelColorSmall: whiteOnly,
);
